#!/bin/python3

import math
import os
import random
import re
import sys



# Complete the solve function below.
def solve(s):
    words = s.split(' ')
    capitalized = [
        word[:1].upper() + word[1:] if word else ''
        for word in words
    ]
    return ' '.join(capitalized)


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
